ci: abort if failed test

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -6,7 +6,7 @@ on:
       - chore/setup-test # Change this to your main branch name
 
 jobs:
-  test:
+  build-and-test:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout code
@@ -22,4 +22,10 @@ jobs:
         run: yarn --frozen-lockfile
 
       - name: Run Jest tests
-        run: yarn test
+        run: |
+          yarn test
+          exit_code=$?
+          if [ $exit_code -ne 0 ]; then
+           echo "Unit tests failed with exit code $exit_code. Stopping the workflow."
+           exit $exit_code
+          fi
